### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/modulo-3-evaluacion-intermedia-albasmg#1]
Buen trabajo @albasmg !

### Algunas pistas para acabarlo:

- [x] Lo suyo es que los pokemons estén en una lista `ul` u `ol`.
- [x] Mueve el `li` fuera del componente 'Pokemon', de esta manera Pokemon es un componente con una tarjeta que podemos usar en diferentes sitios y no solo dentro de un `ul`
- [x] Pinta los tipos con un `ul` y varios `li`
- [x] Usa propTypes para comprobar el tipo de dato de las props

### Cuando tengas esto si quieres puedes:

1. Añadir un click a Pokemon que: marca o desmarca el pokemon como favorito en el array del estado de App.
1. Pasar este dato al componente Pokemon por props
1. Pintar Pokemon con otros estilos cuando por props nos llegue la info de que el pokemon es favorito

Si tienes cualquier duda, avisa!

Al turrón!!!

**Comment by albasmg** [comment]
Hola @migueldelmazo!

Ya he hecho las correcciones, los PropTypes ya los tenia metidos de antes, por si era un error!

Gracias!
